causes [ocaml/typing/env.ml] to not match its interface
I get the error below when running [make] on this commit
```
File "ocaml/env.ml", line 1:
Error: The implementation ocaml/env.ml
       does not match the interface ocaml/.ocamlcommon.objs/byte/env.cmi:
       Values do not match:
         val register_uid :
           Types.Uid.Tbl.key ->
           loc:Location.t -> attributes:Parsetree.attribute list -> unit
       is not included in
         val register_uid :
           Types.Uid.t ->
           loc:Location.t ->
           attributes:Parsetree.attribute list -> unit -> unit
       The type
         Types.Uid.Tbl.key ->
         loc:Location.t -> attributes:Parsetree.attribute list -> unit
       is not compatible with the type
         Types.Uid.t ->
         loc:Location.t ->
         attributes:Parsetree.attribute list -> unit -> unit
       Hint: Did you forget to wrap the expression using `fun () ->'?
       File "ocaml/typing/env.mli", line 22, characters 0-97:
         Expected declaration
       File "ocaml/typing/env.ml", line 49, characters 4-16:
         Actual declaration
File "ocaml/typing/typemod.ml", lines 1636-1637, characters 8-42:
Error: This expression has type unit -> unit
       but an expression was expected of type unit
       because it is in the left-hand side of a sequence
       Hint: Did you forget to provide `()' as argument?
make: *** [ocaml/Makefile.common-jst:66: boot-compiler] Error 1
EXIT STATUS 2
```

Note that [ocaml/env.ml] is not a valid filepath